# Operational Settings
logging.level.org.springframework.web=TRACE
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
logging.level.com.azure.spring.cloud.autoconfigure.keyvault=DEBUG
management.endpoints.web.exposure.include=env,health
mybatis.mapper-locations=classpath:mapper/*.xml
spring.cloud.azure.keyvault.secret.property-sources[0].enabled=true
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=https://kv-ap-pre-me-rgnl-001.vault.azure.net/
spring.cloud.azure.keyvault.secret.property-sources[0].credential.managed-identity-enabled=true
spring.mvc.log-request-details=true
# Secret Configuration (Key Vault values will override these)
azure.notification-hub.shared-access-key-name-t=${ntf-sakname-toyota}
azure.notification-hub.shared-access-key-t=${ntf-sak-toyota}
azure.notification-hub.shared-access-key-name-l=${ntf-sakname-lexus}
azure.notification-hub.shared-access-key-l=${ntf-sak-lexus}
personalinfo.api.key=${ntf-personalinfo-apikey}
jsap.getuserid.xapikey=${ntf-getuserid-apikey}
jsap.getuserinfo.xapikey=${ntf-getuserinfo-apikey}
jsap.dvclink.xapikey=${ntf-dvclink-apikey}
jsap.notification.xapikey=${ntf-notification-apikey}
sendgrid.api.key=${ntf-sendgrid-apikey}
sms-country.user=${ntf-smscountry-user}
sms-country.pass=${ntf-smscountry-pass}
spring.datasource.url=${ntf-datasource-url}
spring.datasource.username=${ntf-datasource-username}
spring.datasource.password=${ntf-datasource-password}
spring.datasource.driver-class-name=org.postgresql.Driver
# Runtime Configuration (Default values)
azure.notification-hub.retry-count=3
azure.notification-hub.api-version=2015-01
azure.notification-hub.installation-uri=https://%s.servicebus.windows.net/%s/installations/%s?api-version=%s
azure.notification-hub.root-uri=https://%s.servicebus.windows.net/%s
azure.notification-hub.sas.ttlSeconds=500
azure.notification-hub.http.timeoutMillis=3000
azure.notification-hub.namespace-t=ntfns-toyota-pre-me-rgnl-001
azure.notification-hub.hub-name-t=ntf-toyota-pre-me-rgnl-001
azure.notification-hub.namespace-l=ntfns-lexus-pre-me-rgnl-001
azure.notification-hub.hub-name-l=ntf-lexus-pre-me-rgnl-001
azure.notification-hub.sas.template=SharedAccessSignature sr=%s&sig=%s&se=%d&skn=%s
azure.notification-hub.sdk.connection-string=Endpoint=sb://%s.servicebus.windows.net/;SharedAccessKeyName=%s;SharedAccessKey=%s
azure.notification-hub.installation.payload.template={\"installationId\":\"%s\",\"platform\":\"gcm\",\"pushChannel\":\"%s\",\"tags\":[\"%s\"]}
azure.notification-hub.payload.template={\"message\":{\"notification\":{\"title\":\"%s\",\"body\":\"%s\"}}}
jsap.getuserid.api.url=https://{ドメイン名}/services/GetUserIdOrInternaluserId
jsap.getuserinfo.api.url=https://{ドメイン名}/services/GetUserInfo
jsap.dvclink.api.url=https://{ドメイン名}/services/GetDvcLinkInfo
jsap.notification.api.url=https://{ドメイン名}/services/Push
ntfinfo.upsert.retry.count=3
ntfinfo.upsert.retry.base-interval=100
ntfinfo.upsert.retry.max-interval=20000
personalinfo.api.url=https://pre-ops-az.t-connect-me.com/user-info-ui/personalInfo/retrieval
sendgrid.from.address-T=info@toyota-connect.com
sendgrid.from.name-T=TOYOTA CONNECT
sendgrid.from.address-L=info@lexus-connect.com
sendgrid.from.name-L=LEXUS CONNECT
sms-country.sender-id-t=T Connect
sms-country.sender-id-l=L Connect
sms-country.api-url=http://smscountry.com/SMSCwebservice_Bulk.aspx