# Azure Key Vault
spring.cloud.azure.keyvault.secret.property-sources[0].enabled=true
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=https://notificationkey.vault.azure.net/
spring.cloud.azure.keyvault.secret.property-sources[0].credential.managed-identity-enabled=true

# Secrets
azure.notification-hub.shared-access-key-name-t=${shared-access-key-name-toyota}
azure.notification-hub.shared-access-key-t=${shared-access-key-toyota}
azure.notification-hub.shared-access-key-name-l=${shared-access-key-name-lexus}
azure.notification-hub.shared-access-key-l=${shared-access-key-lexus}
sendgrid.api.key=${sendgrid-api-key}
sms-country.user=${smscountry-user}
sms-country.pass=${smscountry-pass}
spring.datasource.url=${datasource-url}
spring.datasource.username=${datasource-username}
spring.datasource.password=${datasource-password}
spring.datasource.driver-class-name=org.postgresql.Driver

# AzureNotificationHub 
azure.notification-hub.retry-count=3
azure.notification-hub.api-version=2015-01
azure.notification-hub.installation-uri=https://%s.servicebus.windows.net/%s/installations/%s?api-version=%s
azure.notification-hub.root-uri=https://%s.servicebus.windows.net/%s
azure.notification-hub.sas.ttlSeconds=600
azure.notification-hub.http.timeoutMillis=15000
azure.notification-hub.namespace-t=namespace-notification-platform
azure.notification-hub.hub-name-t=hub-notification-platform
azure.notification-hub.namespace-l=namespace-notification-platform
azure.notification-hub.hub-name-l=hub-notification-platform
azure.notification-hub.sas.template=SharedAccessSignature sr=%s&sig=%s&se=%d&skn=%s
azure.notification-hub.sdk.connection-string=Endpoint=sb://%s.servicebus.windows.net/;SharedAccessKeyName=%s;SharedAccessKey=%s
azure.notification-hub.installation.payload.template={\"installationId\":\"%s\",\"platform\":\"gcm\",\"pushChannel\":\"%s\",\"tags\":[\"%s\"]}
azure.notification-hub.payload.template={\"message\":{\"notification\":{\"title\":\"%s\",\"body\":\"%s\"}}}

# SendGrid
sendgrid.from.address-T=tadatoshi.yamato.bp@jp.nttdata.com
sendgrid.from.name-T=/resource.Toyota
sendgrid.from.address-L=tadatoshi.yamato.bp@jp.nttdata.com
sendgrid.from.name-L=/resource.Lexus

# SMS Country
sms-country.sender-id-t=TOYOTA
sms-country.sender-id-l=LEXUS
sms-country.api-url=http://smscountry.com/SMSCwebservice_Bulk.aspx

# DB関連
ntfinfo.upsert.retry.count=3
ntfinfo.upsert.retry.base-interval=100
ntfinfo.upsert.retry.max-interval=20000
mybatis.mapper-locations=classpath:mapper/*.xml

# 個人情報取得API
personalinfo.api.url=https://personalinfo.api.example.com/getInfo

# リクエスト/ハンドラのマッピングの詳細ログ
logging.level.org.springframework.web=TRACE
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
spring.mvc.log-request-details=true
logging.level.com.azure.spring.cloud.autoconfigure.keyvault=DEBUG
management.endpoints.web.exposure.include=env,health