# Operational Settings
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=https://notificationkey.vault.azure.net/

registernotification.url=https://apim-cmn-pre-me-rgnl-001.azure-api.net/oneserver/v1/services/registernotification
parallel.current=1