# Operational Settings
logging.level.org.springframework.web=TRACE
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
logging.level.com.azure.spring.cloud.autoconfigure.keyvault=DEBUG
management.endpoints.web.exposure.include=env,health
mybatis.mapper-locations=classpath:mapper/*.xml
spring.cloud.azure.keyvault.secret.property-sources[0].enabled=true
spring.cloud.azure.keyvault.secret.property-sources[0].credential.managed-identity-enabled=true
spring.mvc.log-request-details=true
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.driver-class-name=org.postgresql.Driver

# Secret Configuration (Key Vault values will override these)
# shared-access-keys
azure.notification-hub.shared-access-key-name-t=${ntf-sakname-toyota}
azure.notification-hub.shared-access-key-t=${ntf-sak-toyota}
azure.notification-hub.shared-access-key-name-l=${ntf-sakname-lexus}
azure.notification-hub.shared-access-key-l=${ntf-sak-lexus}
# internal-api-keys
personalinfo.api.key=${ntf-personalinfo-apikey}
personalinfolist.api.key=${ntf-personalinfolist-apikey}
registernotification.api.key=${ntf-registernotification-apikey}
sendgrid.api.key=${ntf-sendgrid-apikey}
# payload-modification-elements
silent.push.lockeys=${ntf-silent-push-lockeys}
# smscountry-credentials
sms-country.user=${ntf-smscountry-user}
sms-country.pass=${ntf-smscountry-pass}
# datasource
spring.datasource.url=${ntf-datasource-url}
spring.datasource.username=${ntf-datasource-username}
spring.datasource.password=${ntf-datasource-password}
spring.datasource.host=${ntf-datasource-host}
spring.datasource.port=${ntf-datasource-port}
spring.datasource.name=${ntf-datasource-name}
# bat-threads
thread.pool=${thread-pool}
thread.queue=${thread-queue}
# urls
registernotification.url=${ntf-registernotification-url}
azure.notification-hub.installation-uri=${ntf-installation-url}
azure.notification-hub.root-uri=${ntf-notificationhub-url}
jsap.getuserid.api.url=${ntf-getuserid-url}
jsap.getuserinfo.api.url=${ntf-getuserinfo-url}
jsap.dvclink.api.url=${ntf-dvclink-url}
jsap.notification.api.url=${ntf-execnotifcation-url}
personalinfo.api.url=${ntf-onpremises-url}
personalinfolist.api.url=${ntf-onpremises-list-url}
sms-country.api-url=${ntf-sms-url}

# Runtime Configuration (Default values)
azure.notification-hub.retry-count=3
azure.notification-hub.api-version=2015-01
azure.notification-hub.sas.ttlSeconds=500
azure.notification-hub.http.timeoutMillis=3000
azure.notification-hub.namespace-t=ntfns-toyota-pre-me-rgnl-001
azure.notification-hub.hub-name-t=ntf-toyota-pre-me-rgnl-001
azure.notification-hub.namespace-l=ntfns-lexus-pre-me-rgnl-001
azure.notification-hub.hub-name-l=ntf-lexus-pre-me-rgnl-001
azure.notification-hub.sas.template=SharedAccessSignature sr=%s&sig=%s&se=%d&skn=%s
azure.notification-hub.sdk.connection-string=Endpoint=sb://%s.servicebus.windows.net/;SharedAccessKeyName=%s;SharedAccessKey=%s
azure.notification-hub.installation.payload.template={\"installationId\":\"%s\",\"platform\":\"gcm\",\"pushChannel\":\"%s\",\"tags\":[\"%s\"]}
azure.notification-hub.payload.template={\"message\":{\"notification\":{\"title\":\"%s\",\"body\":\"%s\"}}}
ntfinfo.upsert.retry.count=3
ntfinfo.upsert.retry.base-interval=100
ntfinfo.upsert.retry.max-interval=20000
sendgrid.from.address-T=info@toyota-connect.com
sendgrid.from.name-T=TOYOTA CONNECT
sendgrid.from.address-L=info@lexus-connect.com
sendgrid.from.name-L=LEXUS CONNECT
sms-country.sender-id-t=T Connect
sms-country.sender-id-l=L Connect